INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES
(5, '_wp_page_template', 'page-about.php'),
(6, '_wp_page_template', 'page-services.php'),
(7, '_wp_page_template', 'page-contacts.php'),
(8, '_wp_page_template', 'page-vacancies.php'),
(9, '_wp_page_template', 'page-news.php'),
(10, '_wp_page_template', 'service-audit.php'),
(11, '_wp_page_template', 'service-restore.php'),
(12, '_wp_page_template', 'service-legal.php'),
(13, '_wp_page_template', 'service-accounting.php'),
(14, '_wp_page_template', 'service-secretariat.php'),
(15, '_wp_page_template', 'service-consulting.php'),
(16, '_wp_page_template', 'service-tax.php'),
(17, '_wp_page_template', 'service-management.php'),
(18, '_wp_page_template', 'service-automation.php');
