import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:ofarin/l10n/app_localizations.dart';
import '../../../constants/app_colors.dart';
import '../../../constants/app_sizes.dart';
import '../data/task_repository.dart';

class AddTaskDialog extends ConsumerStatefulWidget {
  final String parentId;
  final String childId;
  final VoidCallback onTaskAdded;

  const AddTaskDialog({
    super.key,
    required this.parentId,
    required this.childId,
    required this.onTaskAdded,
  });

  @override
  ConsumerState<AddTaskDialog> createState() => _AddTaskDialogState();
}

class _AddTaskDialogState extends ConsumerState<AddTaskDialog> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _descController = TextEditingController();
  final _rewardController = TextEditingController(text: '5');
  final _penaltyController = TextEditingController(text: '0');
  final _durationController = TextEditingController(text: '20'); // Default minutes

  String _taskType = 'routine'; // 'routine', 'deadline', 'bonus', 'timer_lock'
  String _rewardType = 'stars'; // 'stars', 'fiat'
  DateTime? _selectedDeadline;
  bool _isLoading = false;

  @override
  void dispose() {
    _titleController.dispose();
    _descController.dispose();
    _rewardController.dispose();
    _penaltyController.dispose();
    _durationController.dispose();
    super.dispose();
  }

  void _pickDeadline() async {
    final now = DateTime.now();
    final pickedDate = await showDatePicker(
      context: context,
      initialDate: now.add(const Duration(days: 1)),
      firstDate: now,
      lastDate: now.add(const Duration(days: 365)),
    );

    if (pickedDate != null && mounted) {
      final pickedTime = await showTimePicker(
        context: context,
        initialTime: const TimeOfDay(hour: 18, minute: 0),
      );

      if (pickedTime != null && mounted) {
        setState(() {
          _selectedDeadline = DateTime(
            pickedDate.year,
            pickedDate.month,
            pickedDate.day,
            pickedTime.hour,
            pickedTime.minute,
          );
        });
      }
    }
  }

  void _submit() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() {
      _isLoading = true;
    });

    try {
      final taskRepo = ref.read(taskRepositoryProvider);
      
      final task = TaskModel(
        id: '', // Generated by Repo/DB
        parentId: widget.parentId,
        childId: widget.childId,
        title: _titleController.text.trim(),
        description: _descController.text.trim().isEmpty ? null : _descController.text.trim(),
        taskType: _taskType,
        rewardType: _rewardType,
        rewardAmount: double.tryParse(_rewardController.text) ?? 1.0,
        penaltyAmount: double.tryParse(_penaltyController.text) ?? 0.0,
        status: 'todo',
        deadline: _taskType == 'deadline' ? _selectedDeadline : null,
        timerDurationSeconds: _taskType == 'timer_lock' 
            ? (int.tryParse(_durationController.text) ?? 20) * 60 
            : null,
        createdAt: DateTime.now(),
      );

      await taskRepo.createTask(task);

      if (mounted) {
        widget.onTaskAdded();
        Navigator.pop(context);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Хатогӣ ҳангоми сохтани вазифа: $e'),
            backgroundColor: AppColors.error,
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() {
          _isLoading = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final localizations = AppLocalizations.of(context);
    final String txtCreate = localizations?.createTask ?? 'Иловаи вазифа';
    final String txtTitle = localizations?.taskTitle ?? 'Номи вазифа';
    final String txtTitleHint = localizations?.enterTaskTitle ?? 'Номи вазифаро ворид кунед';
    final String txtType = localizations?.taskType ?? 'Намуди вазифа';
    final String txtRewardType = localizations?.rewardType ?? 'Намуди мукофот';
    final String txtRewardAmt = localizations?.rewardAmount ?? 'Миқдори мукофот';
    final String txtPenaltyAmt = localizations?.penaltyAmount ?? 'Миқдори ҷарима';
    final String txtSave = localizations?.save ?? 'Сабт кардан';
    final String txtCancel = localizations?.cancel ?? 'Баргаштан';

    return Dialog(
      shape: RoundedRectangleBorder(borderRadius: AppSizes.borderRadiusL),
      backgroundColor: Colors.white,
      child: SingleChildScrollView(
        child: Padding(
          padding: const EdgeInsets.all(AppSizes.xl),
          child: Form(
            key: _formKey,
            child: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                // Dialog Title
                Text(
                  txtCreate,
                  textAlign: TextAlign.center,
                  style: const TextStyle(
                    fontSize: 20,
                    fontWeight: FontWeight.bold,
                    color: AppColors.textPrimaryLight,
                  ),
                ),
                AppSizes.spaceL,

                // Task Name Field
                TextFormField(
                  controller: _titleController,
                  keyboardType: TextInputType.text,
                  decoration: InputDecoration(
                    labelText: txtTitle,
                    hintText: txtTitleHint,
                    prefixIcon: const Icon(Icons.assignment_outlined),
                  ),
                  validator: (value) {
                    if (value == null || value.trim().isEmpty) {
                      return 'Илтимос, номи вазифаро ворид созед';
                    }
                    return null;
                  },
                ),
                AppSizes.spaceL,

                // Description Field
                TextFormField(
                  controller: _descController,
                  maxLines: 2,
                  decoration: const InputDecoration(
                    labelText: 'Тавсифи вазифа (Description)',
                    hintText: 'Масалан: тоза кардани чанг, ҷобаҷо кардани китобҳо...',
                    prefixIcon: Icon(Icons.description_outlined),
                  ),
                ),
                AppSizes.spaceL,

                // Task Type Dropdown
                DropdownButtonFormField<String>(
                  initialValue: _taskType,
                  decoration: InputDecoration(
                    labelText: txtType,
                    prefixIcon: const Icon(Icons.category_outlined),
                  ),
                  items: [
                    DropdownMenuItem(
                      value: 'routine',
                      child: Text(localizations?.routine ?? 'Рӯзҳои муқаррарӣ (Реҷа)'),
                    ),
                    DropdownMenuItem(
                      value: 'deadline',
                      child: Text(localizations?.deadlineBound ?? 'Вазифа бо муҳлат'),
                    ),
                    DropdownMenuItem(
                      value: 'bonus',
                      child: Text(localizations?.bonusChore ?? 'Вазифаи бонусӣ'),
                    ),
                    DropdownMenuItem(
                      value: 'timer_lock',
                      child: Text(localizations?.timerLock ?? 'Таймери ҳатмӣ'),
                    ),
                  ],
                  onChanged: (val) {
                    if (val != null) {
                      setState(() {
                        _taskType = val;
                      });
                    }
                  },
                ),
                AppSizes.spaceL,

                // Extra configuration inputs based on Task Type
                if (_taskType == 'deadline') ...[
                  InkWell(
                    onTap: _pickDeadline,
                    child: Container(
                      padding: const EdgeInsets.symmetric(horizontal: AppSizes.l, vertical: AppSizes.m),
                      decoration: BoxDecoration(
                        border: Border.all(color: AppColors.borderLight, width: 1.5),
                        borderRadius: AppSizes.borderRadiusM,
                      ),
                      child: Row(
                        children: [
                          const Icon(Icons.calendar_month_outlined, color: AppColors.primary),
                          AppSizes.spaceM,
                          Text(
                            _selectedDeadline == null
                                ? 'Муҳлатро интихоб кунед (Pick Deadline)'
                                : 'Муҳлат: ${_selectedDeadline!.day}/${_selectedDeadline!.month} ${_selectedDeadline!.hour.toString().padLeft(2, '0')}:${_selectedDeadline!.minute.toString().padLeft(2, '0')}',
                            style: const TextStyle(fontWeight: FontWeight.w600, fontSize: 14),
                          ),
                        ],
                      ),
                    ),
                  ),
                  AppSizes.spaceL,
                ],

                if (_taskType == 'timer_lock') ...[
                  TextFormField(
                    controller: _durationController,
                    keyboardType: TextInputType.number,
                    decoration: const InputDecoration(
                      labelText: 'Давомнокии таймер (дақиқа)',
                      prefixIcon: Icon(Icons.timer_outlined),
                    ),
                    validator: (value) {
                      final n = int.tryParse(value ?? '');
                      if (n == null || n <= 0) {
                        return 'Илтимос, дақиқаи мусбатро ворид кунед';
                      }
                      return null;
                    },
                  ),
                  AppSizes.spaceL,
                ],

                // Reward & Currency Row
                Row(
                  children: [
                    // Currency Type Dropdown
                    Expanded(
                      flex: 4,
                      child: DropdownButtonFormField<String>(
                        initialValue: _rewardType,
                        decoration: InputDecoration(
                          labelText: txtRewardType,
                          contentPadding: const EdgeInsets.symmetric(horizontal: AppSizes.s),
                        ),
                        items: [
                          DropdownMenuItem(
                            value: 'stars',
                            child: Text(localizations?.stars ?? 'Ситораҳо'),
                          ),
                          DropdownMenuItem(
                            value: 'fiat',
                            child: Text(localizations?.fiat ?? 'Сомонӣ'),
                          ),
                        ],
                        onChanged: (val) {
                          if (val != null) {
                            setState(() {
                              _rewardType = val;
                              // Update default value accordingly
                              _rewardController.text = val == 'stars' ? '5' : '3.00';
                            });
                          }
                        },
                      ),
                    ),
                    const SizedBox(width: AppSizes.m),
                    
                    // Reward Value Input
                    Expanded(
                      flex: 4,
                      child: TextFormField(
                        controller: _rewardController,
                        keyboardType: TextInputType.number,
                        decoration: InputDecoration(
                          labelText: txtRewardAmt,
                        ),
                        validator: (value) {
                          final n = double.tryParse(value ?? '');
                          if (n == null || n <= 0.0) {
                            return 'Супурда шавад';
                          }
                          return null;
                        },
                      ),
                    ),
                  ],
                ),
                AppSizes.spaceL,

                // Penalty Field
                TextFormField(
                  controller: _penaltyController,
                  keyboardType: TextInputType.number,
                  decoration: InputDecoration(
                    labelText: txtPenaltyAmt,
                    prefixIcon: const Icon(Icons.trending_down_rounded, color: AppColors.error),
                    helperText: 'Агар кӯдак супоришро иҷро накунад, ситора/маблағ кам мешавад',
                  ),
                  validator: (value) {
                    final n = double.tryParse(value ?? '');
                    if (n == null || n < 0.0) {
                      return 'Қимати нодуруст';
                    }
                    return null;
                  },
                ),
                AppSizes.spaceXL,

                // Actions buttons row
                Row(
                  children: [
                    Expanded(
                      child: OutlinedButton(
                        onPressed: _isLoading ? null : () => Navigator.pop(context),
                        style: OutlinedButton.styleFrom(
                          minimumSize: const Size.fromHeight(48),
                          side: const BorderSide(color: AppColors.borderLight, width: 1.5),
                          shape: RoundedRectangleBorder(
                            borderRadius: AppSizes.borderRadiusM,
                          ),
                        ),
                        child: Text(
                          txtCancel,
                          style: const TextStyle(
                            color: AppColors.textSecondaryLight,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                      ),
                    ),
                    const SizedBox(width: AppSizes.m),
                    Expanded(
                      child: Container(
                        height: 48,
                        decoration: BoxDecoration(
                          gradient: AppColors.primaryGradient,
                          borderRadius: AppSizes.borderRadiusM,
                        ),
                        child: ElevatedButton(
                          onPressed: _isLoading ? null : _submit,
                          style: ElevatedButton.styleFrom(
                            backgroundColor: Colors.transparent,
                            shadowColor: Colors.transparent,
                            minimumSize: const Size.fromHeight(48),
                            elevation: 0,
                          ),
                          child: _isLoading
                              ? const SizedBox(
                                  width: 20,
                                  height: 20,
                                  child: CircularProgressIndicator(
                                    color: Colors.white,
                                    strokeWidth: 2,
                                  ),
                                )
                              : Text(
                                  txtSave,
                                  style: const TextStyle(
                                    fontWeight: FontWeight.bold,
                                    color: Colors.white,
                                  ),
                                ),
                        ),
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
